version: '3'

services:
  wppconnect-server-hml:
    build:
      context: ./wppconnect/wppconnect-server  # Corrected the path here
      dockerfile: Dockerfile
    restart: always
    image: wppconnect-server-hml
    hostname: wppconnect-server-hml
    entrypoint: ["docker-entrypoint.sh", "yarn", "dev"]
    environment:
      - SECRET_KEY_SERVER=${SECRET_KEY_SERVER}
      - PORT=${PORT}
    ports:
      - "8098:21483"
    networks:
      - wpp-network
    tty: true
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M

          
networks:
  wpp-network:
    name: wpp-network
    driver: bridge
