apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: developer
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1dUQ0NBVUVDQVFBd0ZERVNNQkFHQTFVRUF3d0paR1YyWld4dmNHVnlNSUlCSWpBTkJna3Foa2lHOXcwQgpBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFyY3lGWVJzU2puNWIvaEVpdjhNU2ZqV3RiSnE2VElVOFhJZnNtck4yCmJyRmZBTnNaeUZ0ZXl2R29ua0gwUHRRR2FoT0lPaDRySUwyVEVPTDEyaWo3U0h5VVZUaXllZE1hUUtoWWdlUGEKTmxhL0hvN3FSY1VMVGtsN2YvOC9JRitadWY4ZFB2THpIaW9rSlJ6WjNVT0liZm90RUJFSDFKUE51UENrN2ZIMwpkNy85b08yNlM0ZldIY0xOZFpVeDA3aFVHOUk3ZTJyRUgvUUROdlZaN1V2WG9BY05hRlcrSVJ6YWVBK2hDL0ZlClZaYUljQldNSnJzTEJMOVhCY28ycTI4S3p3MHlkRFJJUnJadEw5S0pDVkN5UWFBeUR0d3ZrcDVMVFhlQUJJdS8KMVJOSURmWHI0aE1LOW5HeFpWZWI5ZnJCbVIwa2NkM0d5M2d3MHBlK3h1UmNzUUlEQVFBQm9BQXdEUVlKS29aSQpodmNOQVFFTEJRQURnZ0VCQUgrakJPU01vT0llSm5XNkNKOFlUa1FqTGFIVGtzZG5VRUlTUWR3TFp5bTk2bENXCjl0bFRRVDFiT0twWW82djFQTm4rTFdUbk8yZXplMlBIYmxxYzNGMWFveDVRakp0QWlHMGk4L1pvdWlRRDJ2Y3YKRG5CNGo3VXZPa1B6eno5U0tUV2V0WXBxd2lhR2JTYmVGSE1tV05FZkpINnJXRXFNQlM2ZHBhbno3ekdyZFg0Kwp1OVBUdzhYNWRnenF2VjBGTVQ3SzVhdmQwdFc0Mzl5ZTRJUEVuZnpERVFnM0pxdFBuWnUxQllMSllsTVZzbVJVCktjRDltVzF0OEpLNmk5cGxXKzg4VHI4RDVEZ2lwSXJ5Y29SUmFSaTNBNmVwRzhjZlhBbDZ0TmYyRU4xcEo4eVcKMzdCL3pkTUpRMFB6SWtXWjFINjU2LzhhekYzMzlOb1pvbDFxY1BBPQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 31536000 # 1 year
  usages:
  - client auth

